export const data = [{
  id: "beaDog",
  name: "Bea",
  species: "Perro",
  personality: "Dulce",
  gender: "Femenino",
  shortDescription: "Perro deportista y enérgico, amante del ejercicio y las competiciones.",
  description: "Bea es un perro orgulloso y elegante que se considera a sí misma una autoridad en moda y alta sociedad en Animal Crossing. Siempre está al tanto de las últimas tendencias y eventos de la alta sociedad. Bea se enorgullece de su elegancia y buen gusto, y a menudo ofrece consejos de moda a los demás habitantes. Aunque puede parecer algo distante al principio, aprecia la amistad genuina y siempre está dispuesta a ayudar a sus amigos. ¡Celebra su cumpleaños el 15 de octubre!",
  imageUrl:"https://dodo.ac/np/images/thumb/c/c2/Bea_NH.png/150px-Bea_NH.png",
  facts: {
    zodiacSign: "Leo",
    catchPhrase: "¡A darlo todo!",
    birthDate: "15 de octubre",
  },
},
{
  id: "biskitDog",
  name: "Biskit",
  species: "Perro",
  personality: "Perezoso",
  gender: "Masculino",
  shortDescription: "Perro despreocupado y amante de las galletas, siempre con un hambre insaciable.",
  description: "Biskit es un perro despistado con una personalidad relajada y amigable en Animal Crossing. Siempre parece estar en su propio mundo y es conocido por su actitud despreocupada. A menudo se le encuentra tarareando melodías alegres y disfrutando de la vida sin preocupaciones. Biskit es fácil de llevar y se lleva bien con otros habitantes del pueblo. Su catchphrase es '¡bork!', reflejando su naturaleza canina. Aunque su cabeza pueda estar en las nubes, su corazón está siempre en el lugar correcto, y es un amigo leal para todos en el pueblo. Biskit celebra su cumpleaños el 13 de mayo.",
  imageUrl: "https://dodo.ac/np/images/thumb/7/78/Biskit_NH.png/150px-Biskit_NH.png",
  facts: {
    zodiacSign: "Piscis",
    catchPhrase: "¡Guau galleta!",
    birthDate: "13 de mayo",
  },
},
{
  id: "der11",
  name: "Yuki",
  species: "Ciervo",
  personality: "Vivaracha",
  gender: "Femenino",
  imageUrl: "https://dodo.ac/np/images/2/26/Shino_amiibo.png",
  shortDescription: "Yuki es una aldeana ciervo animada en la serie Animal Crossing",
  description: "Yuki en una cierva de color blanco amarillento con un hocico de color blanco y pesuñas de color dorado. Yuki tiene unos ojos alargados de color amarillo con una sombra de ojos de color rojo del estilo Hikimayu, además de unos pequeños colmillos que sobresalen de su boca y podrían indicar que pertenece a la especie del ciervo de copete. El diseño de Shino parece estar inspirado por máscaras del teatro Noh japonés, más concretamente a la mascara de los Hannya, demonios de mujeres consumidas por los celos.",
  facts: {
    zodiacSign: "Libra",
    birthDate: "31/10",
    catchPhrase: "oni"
  },
},
{
  id: "goa09",
  name: "Morfeo",
  species: "Cabra",
  personality: "Perezoso",
  gender: "Masculino",
  imageUrl: "https://dodo.ac/np/images/thumb/1/18/Sherb_NH.png/150px-Sherb_NH.png",
  shortDescription: "Morfeo es un aldeano cabra perezoso en la serie Animal Crossing",
  description: "Morfeo tiene la personalidad vaga, por lo que será amigable y fácil de tratar debido a su estilo de vida relajado. Como a todos los vecinos vagos, a Morfeo le encanta comer y el descansar, disfrutará de participar en sus pasatiempos comunes, que generalmente tienen que ver con relajarse o comer, como la pesca. Morfeo se llevará bien con los otros vecinos, pero puede ofender o confundir a los vecinos deportistas, que tienen un estilo de vida de lleno de ejercicio y de buen estado físico, en comparación con el estilo de vida perezoso de Morfeo.",
  facts: {
    zodiacSign: "Capricornio",
    birthDate: "18/1",
    catchPhrase: "bostezzz",
  },
},
];